### ISSUE TITLE
Window tiling

### ISSUE THREAD

**Issue by WuerfelDev** [amezin/gnome-shell-extension-ddterm#18]
I'm using the pop-shell window tiling. When I open the terminal it starts as tiled window.

Maybe it's possible to add some xprop flag to keep it in a floating state
(Not sure but maybe window type dialog )

**Comment by amezin** [comment]
As far as I understand from the code, pop shell has a user configurable list of exceptions (windows that shouldn't be tiled): https://github.com/pop-os/shell/blob/master/src/window.ts#L261
`wmclass` of the terminal window is `Com.github.amezin.ddterm`

**Comment by WuerfelDev** [comment]
> As far as I understand from the code, pop shell has a user configurable list of exceptions (windows that shouldn't be tiled): https://github.com/pop-os/shell/blob/master/src/window.ts#L261
> `wmclass` of the terminal window is `Com.github.amezin.ddterm`

I know, but there are also other tiling window manager, so i'm wondering if it's possible to find a general solution, so it is handled everywhere as a floating window by default

**Comment by amezin** [comment]
I'm not aware of any generiс/standardized protocol for that.
Making the window override-redirect/popup will probably exclude it from all window management extensions... But it'll also hide ddterm window from its own shell extension I guess.
Marking the window as "dialog" should work too.. But looks like a hack because it's not actually a dialog.
Setting window type to dock/panel doesn't work on Wayland... And I had issues with input focus on X11 with "dock" window.
I'll need to retest these options when I'll have time

**Comment by WuerfelDev** [comment]
It's working fine with the pop shell exclusion, so this is low priority  :)

**Comment by amezin** [comment]
Changing the window type hint to 'Dialog' changes show/hide animations on X11 (and they look really bad IMO), so I don't want to change the default value. Instead, I've added "Window type hint" parameter to preferences ("Window" tab), so you can set that to "Dialog" if you want. Though it doesn't seem to work on Wayland at all :(
