### ISSUE TITLE
Preserve working directory when opening new tabs

### ISSUE THREAD

**Issue by szarnyasg** [amezin/gnome-shell-extension-ddterm#46]
Many thanks for this project! This terminal my daily driver after unsuccessful attempts at getting others (Guake, Yakuake, Drop Down Terminal, Drop Down Terminal X, etc.) to work properly.

I'm looking for a feature that allows keeping the working directory when opening a new tab. The GNOME terminal calls this feature "preserve working directory". I was unable to find such an option in ddterm's settings.

**Comment by ZennMystic** [comment]
journalctl -f
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
Nov 27 14:20:00 debian-pc gnome-shell[3044]: >                   X11 cannot support keycodes above 255.
Nov 27 14:20:00 debian-pc gnome-shell[3044]: Errors from xkbcomp are not fatal to the X server
Nov 27 14:20:00 debian-pc systemd[1879]: Starting org.gnome.SettingsDaemon.XSettings.service - GNOME XSettings service...
Nov 27 14:20:01 debian-pc systemd[1879]: Started org.gnome.SettingsDaemon.XSettings.service - GNOME XSettings service.
Nov 27 14:20:01 debian-pc systemd[1879]: Reached target gnome-session-x11-services-ready.target - GNOME session X11 services.
Nov 27 14:20:01 debian-pc gnome-shell[2078]: ATK Bridge is disabled but a11y has already been enabled.
Nov 27 14:20:01 debian-pc firefox-esr.desktop[3000]: ATTENTION: default value of option mesa_glthread overridden by environment.
Nov 27 14:20:01 debian-pc firefox-esr.desktop[3000]: ATTENTION: default value of option mesa_glthread overridden by environment.
Nov 27 14:20:12 debian-pc gnome-shell[2078]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 27 14:20:35 debian-pc gnome-shell[2078]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Nov 27 14:21:06 debian-pc systemd[1879]: Started vte-spawn-3355180d-7243-4402-b972-04a4dadfcc0c.scope - VTE child process 3702 launched by com.github.amezin.ddterm process 2934.
Nov 27 14:21:20 debian-pc gnome-shell[2078]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

I am really sorry and I hate to waste you time. But since reporting this it has starting working. I do not know what to tell you. All I did was untick and re-tick a few of the setting around the preserve working directory.  I swear I'd tried that already and was not working.  But now it is.  One thing I have notice in trying options is the show tab bar: Automatic does not work. always or never works fine though.

Very sorry about this. I know I'm not being helpful really. I love the extension BTW. more so since getting working directory to work

**Comment by amezin** [comment]
I see no related errors in the log...

Please create a separate bug report: https://github.com/ddterm/gnome-shell-extension-ddterm/issues/new?assignees=&labels=bug&projects=&template=BUG.yml
